config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# READ ALL 
  get "tasks", to: "tasks#index"

# CREATE
# GET and POST form
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create", as: :create_task
  
# READ ONE
  get "tasks/:id", to: "tasks#show", as: :task # in flashcards it is as: :restaurant. CONVENTION?
# UPDATE(edit)
  # GET form
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update", as: :update_task

# DELETE
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_task, only: [:show, :edit, :update, :destroy]
    # READ ALL
    def index
        @tasks = Task.all
    end
    # CREATE
    # GET
    def new
        @task = Task.new #params[:task]
    end
    # POST
    def create
        @task = Task.new(task_params) # create with permitted params
        @task.save

        redirect_to task_path(@task)
    end
    # READ ONE
    def show
    end

    #UPDATE
    def edit
    end

    def update
        @task.update(task_params)
    end

    # DELETE ONE

    def destroy
     @task = @task.destroy

    redirect_to task_path(@task)
    end

    private

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end

    def set_task
        @task = Task.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container"> 
    <%= yield %>
  </div> 
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f|  %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.button :submit%>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f|  %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
     <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> Tasks To Do: <h1>
<ul> 
    <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task)  %></li>
   <%#= <i class="far fa-trash-alt"><%= link_to 
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?"}  task_path(task)%>
    <%end%>
</ul>
<%= link_to "Add a task", tasks_new_path %> 

app/views/tasks/new.html.erb
<h2>Create a new task</h2>
<%= simple_form_for(@task) do |f|  %>
    <%= f.input :title, label: "Name of Task" %>
    <%= f.input :details, placeholder: "Write a short description about your task" %>
     <%= f.button :submit%>
<% end %>
<%= link_to "Back to list", tasks_path %>
<%= link_to "Add another task", tasks_new_path %>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1> How to complete the tasks:</h1>
<p><%= @task.details %></p>
<%= link_to "Edit task", edit_task_path %>
<%= link_to "Delete #{@task.title}", 
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?"} %>
<%= link_to "Back to list", tasks_path %>
<%= link_to "Add another task", tasks_new_path %>